<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

$output = "";

try {
    // 1. Find Delivery User
    $user = \App\Models\User::where('username', 'delivery')->first();
    if(!$user) {
        throw new Exception("User 'delivery' not found.");
    }
    $output .= "User found: " . $user->name . " (ID: " . $user->id . ")\n";

    // 2. Create Dummy Order
    $order = \App\Models\Order::create([
        'user_id' => $user->id, // Assign to self just for simplicity, usually customer
        'order_number' => 'ORD-' . strtoupper(uniqid()),
        'total_amount' => 500.00,
        'payment_method' => 'cash_on_delivery',
        'payment_status' => 'pending',
        'status' => 'processing',
        'contact_number' => '09123456789',
        'delivery_address' => 'Test Address ' . rand(1, 100),
        'shipping_cost' => 50.00
    ]);
    $output .= "Created Order: " . $order->order_number . " (ID: " . $order->id . ")\n";

    // 3. Create Delivery Assignment
    $delivery = \App\Models\Delivery::create([
        'order_id' => $order->id,
        'delivery_personnel_id' => $user->id,
        'scheduled_date' => now()->addDays(45), // Far future test
        'status' => 'scheduled',
        'delivery_notes' => 'Test delivery generated by script.'
    ]);
    
    // Update order status
    $order->update(['status' => 'in_transit']);

    $output .= "Created Delivery: " . $delivery->id . " | Status: " . $delivery->status . " | Scheduled: " . $delivery->scheduled_date . "\n";
    $output .= "SUCCESS: Active delivery generated.\n";

} catch (\Exception $e) {
    $output .= "Error: " . $e->getMessage() . "\n";
}

file_put_contents('generation_output.txt', $output);
echo "Done.\n";
